---
r1:
    hostname: 192.168.1.35
    # port: 5042
    username: admin
    password: admin
    platform: ios
    groups:
        - ios
    data:
        site: home
        role: cisco
        type: router
    connection_options:
        napalm:
            extras:
                optional_args: {
                    transport: 'ssh',
                    # global_delay_factor: 2,
                    secret: '',
                    dest_file_system: 'ios' # required for napalm_configure
                    }
        netmiko:
          extras:
              device_type: 'cisco_ios_ssh'
s1:
    hostname: 192.168.1.35
    # port: 5042
    username: admin
    password: admin
    platform: ios
    groups:
        - ios
    data:
        site: home
        role: cisco
        type: router
    connection_options:
        napalm:
            extras:
                optional_args: {
                    transport: 'ssh',
                    # global_delay_factor: 2,
                    secret: '',
                    dest_file_system: 'ios' # required for napalm_configure
                    }
        netmiko:
          extras:
              device_type: 'cisco_ios_ssh'
